### ISSUE TITLE
Defaults from package.json

### ISSUE THREAD

**Issue by jarofghosts** [licenses/lice-js#1]
It would be pretty cool if the information chain for generating the license went something like:

```
(cli options) -> (package.json) -> (what it currently defaults to [ie .gitconfig info and dirname etc])
```

so that once you `npm init` you can run lice and get a license generated for you.

i've forked and started work on adding that functionality, but wanted to run it past you for your thoughts.

**Comment by Daniel1of1** [comment]
This makes sense... But I don't think the chain is particularly intuitive behaviour.

 Agree with getting the type from `package.json` though. perhaps a flag would be nicer `licejs  --package` (possibly a terrible flag name but you get the idea.)

**Comment by Daniel1of1** [comment]
Further. If this flag is selected it could take author, project etc. out of the `package.json` unless overridden by cli options. :)

**Comment by jarofghosts** [comment]
Yeah, that was my thinking exactly... and since the package.json has all of the relevant information for generating the license, I figured it made sense to use that as the default.

**Comment by Daniel1of1** [comment]
Upon further consideration I agree with your original proposal of the information chain. :+1: Happy for a PR.

**Comment by jarofghosts** [comment]
cool, [opened](https://github.com/licenses/lice-js/pull/2)

**Comment by Daniel1of1** [comment]
done in #2 thanks to @jarofghosts yay
